---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hydra-maester.fullname" . }}
  labels:
{{ include "hydra-maester.labels" . | indent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: {{ include "hydra-maester.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: {{ include "hydra-maester.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.maester.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.maester.image.repository }}:{{ .Values.maester.image.tag }}"
          imagePullPolicy: {{ .Values.maester.image.pullPolicy }}
          command:
            - /manager
          args:
            - --metrics-addr=127.0.0.1:8080
            - --hydra-url={{ .Values.maester.adminProto }}://{{ include "hydra.fullname" . }}-admin
            {{- if .Values.maester.forwardedProto }}
            - --forwarded-proto={{ .Values.maester.forwardedProto }}
            {{- end }}
            - --hydra-port={{ .Values.service.admin.port }}
          resources:
            {{- toYaml .Values.maester.deployment.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      serviceAccountName: {{ include "hydra-maester.name" . }}-account
      nodeSelector:
      {{- with .Values.maester.deployment.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.maester.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.maester.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
